### ISSUE TITLE
prev_pred_embds

### ISSUE THREAD

**Issue by mattyd2** [sanyam5/skip-thoughts#2]
Thanks for the implementation. 

[Is this correct](https://github.com/sanyam5/skip-thoughts/blob/master/model.py#L81-L82)? Specifically using the `next_thoughts` with the `delayed_prev_word_embeddings` and the `prev_thoughts` with the `delayed_next_word_embeddings`?

I was looking at a TF implementation and didn't see this approach implemented. If it's correct can you explain why?

Thanks,

**Comment by sanyam5** [comment]
I do think it's correct. But I agree it might seem confusing at first. I'll try to explain.

Let's say we are trying to generate the next sentence word by word. We do this conditioned on the Thought vector of *previous* sentence. Also we want to guide the generation process by teacher forcing. In teacher forcing you feed the RNN the word by word ground truth of the sentence that you are actually predicting which in our case is the next sentence. But you give the word by word ground truth after a delay of one word.

Similar argument can be made for the prediction of previous sentence.

Hope this helps!

**Comment by mattyd2** [comment]
I think I understand what your suggesting and why given the way you handle the training data it's setup in this manner.

If I follow, `thoughts` would be represented by `t_0` and you need to step backwards and forwards to predict both `t_-1` and `t_1`.

```
t_-1 = prev_thoughts
t_0 = thoughts
t_1 = next_thoughts
```

It would seem to me that if you randomly selected `t_0` for a given batch size, and maybe implement bucketing so the texts are of approximately equal length, then you could retrieve and encode the corresponding `t_-1` and `t_1` for each `t_0` in the batch and then `prev_pred_embds` and `next_pred_embds` would be conditioned on the `t_0` values in the batch, correct?

Cheers,

**Comment by sanyam5** [comment]
Just one correction
```
t_0 = prev_thoughts
t_1 = next_thoughts
```
The thoughts of each `t_0` predict sentence of the corresponding `t_1` and thoughts of each `t_1` predict the sentence of the corresponding `t_0`.  There is no `t_-1` as they do in the original paper. Sorry for the confusion :/

Best,

**Comment by mattyd2** [comment]
ah. that's helpful.

thanks

**Comment by sanyam5** [comment]
No problem :)
