### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by meoti** [sanyam5/skip-thoughts#3]
Hi Sanyam, 
Are there already some saved  models  based on the BookCorpus we can use with your code?
Thank you.

**Comment by AlJohri** [comment]
@sanyam5 I would also be interested in this. thanks!

**Comment by sanyam5** [comment]
Hi, @meoti very sorry for the delay in replying. @AlJohri thanks for reminding.

There is a GitHub repo which claims to convert the original pre-trained models in theano to PyTorch models. I suggest you check this first and see if you are able to use those pre-trained models. https://github.com/Cadene/skip-thoughts.torch

If that doesn't work we can figure out a way to transfer the pretrained models. However, I only trained the models on 1200 dimensions and not on 2400 dimensions as is done in the original implementation.

**Comment by meoti** [comment]
Thanks for the feedback. I did see the Cadene repo, however, it doesn't fit our needs.... In our project, the implementation itself is slightly changed a bit to be used in a different context, meaning we will have to load similar model dicts in the code and fine tune.

As you mention it also depend on the config for training. 
So in the end, we are training from scratch with in a different implementation.
Thank you.
