### ISSUE TITLE
Is the code something wrong?

### ISSUE THREAD

**Issue by xvshiting** [sanyam5/skip-thoughts#4]
Hi,
  I   appreciate that you like to share your code with us and its really graceful. 
But after I read your code, I think there maybe something wrong in your way to implement SKIP-THOUGHTS。
`return loss, sentences[0], sentences[1], prev_pred_ids, next_pred_ids` 
Above code is the return  in forward function of model.py .  I thought your treat sentences[0] as previous sentence and sentences[1] as next sentence. But skip thought  need use middle sentence to predict two sentences on each side of  it. So I could't understand the input sentence of encoder(your middle sentence).

I think the reasonable way is we feed sentences[1]  into encoder ,  sentences[0] and sentences[2] to prev and next respectively. 

If I miss something ,pleas let me know!

Thanks!

**Comment by sanyam5** [comment]
There is no "middle" sentence in my implementation. Having that would
require 3 forward passes. I implemented in a way that requires just two.
So, sentence [0] is the "previous" sentence of sentence [1]. And sentence
[1] is the "next" sentence of sentence [0].

**Comment by xvshiting** [comment]
Okay！thanks a lot！
