### ISSUE TITLE
embedding sentences 

### ISSUE THREAD

**Issue by loilethanh** [sanyam5/skip-thoughts#5]
How can i embedding new sentences use model pre-train ?

**Comment by zarzen** [comment]
take a look at [https://github.com/sanyam5/skip-thoughts/blob/master/Evaluate.ipynb](),
you can use `usable_encoder.encode(['sentencs1', 'sentence2', ...])` to encode

**Comment by sanyam5** [comment]
@lethanhloiHD sorry for the delay in response. Yes, @zarzen has it right. Thanks @zarzen!
